### ISSUE TITLE
CloudOfThingsRestClient does not close the connection if the request was not successful

### ISSUE THREAD

**Issue by crmolinaz** [cloud-of-things/cot-java-rest-sdk#54]
Hi,

CloudOfThingsPlatform creates a OkHttpClient object that it used for the class CloudOfThingsRestClient.java. When the request failed (user/password not correct, etc.) the connection is not closed by CloudOfThingsRestClient and continues acumulating open sockets until its not possible do more requests.

com.telekom.m2m.cot.restsdk.util.CotSdkException: Error in request
Caused by: java.net.SocketException: Zu viele offene Dateien
        at java.net.Socket.createImpl(Socket.java:460) 
        at java.net.Socket.getImpl(Socket.java:520)
        at java.net.Socket.setSoTimeout(Socket.java:1141) 
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:221) 
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149) 
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195) 
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) 
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) 
        at okhttp3.RealCall.execute(RealCall.java:69) 
        at com.telekom.m2m.cot.restsdk.CloudOfThingsRestClient.getResponse(CloudOfThingsRestClient.java:431)

**Comment by Andyck** [comment]
This issue is fixed and released in version 1.0.4
